
const _selectors = [
    ".class",
    ".class1.class2",
    ".class1 .class2",
    "#id",
    "*",
    "element",
    "element.class",
    "element,element",
    "element element",
    "element>element",
    "element+element",
    "element1~element2",
    "[attribute}",
    "[attribute=value]",
    "[atrribute~=value]",
    "[attribute|=value]",
    "[attribute^=value]",
    "[attribute$=value]",
    "[attribute*=value]",
    ":active",
    "::after",
    "::before",
    ":checked",
    ":defautl",
    ":disabled",
    ":empty",
    ":enabled",
    ":first-child",
    "::first-letter",
    "::first-line",
    ":first-of-type",
    ":focus",
    ":fullscreen",
    ":hover",
    ":in-ranger",
    ":indeterminate",
    ":invalid",
    ":lang(language)",
    ":last-child",
    ":last-of-type",
    ":link",
    "::marker",
    ":not(selector)",
    ":nth-last-child(n)",
    ":nth-last-of-type(n)",
    ":nth-of-type(n)",
    ":only-of-type",
    ":only-child",
    ":optional",
    ":out-of-range",
    "::placeholder",
    ":read-only",
    ":read-write",
    ":required",
    ":root",
    "::selection",
    ":target",
    ":valid",
    ":visited"


]
export default _selectors;