const _string = [
"match()",
"search() ===indexOf() !+ charAt()",
"charAt() !+ search()",
"substring()",
"replace()",
"split",
"concat()",
"repeat()",
"indexOf()",
"prototype",
"length",
"constructor",
"toString()",
"valueOf()",
"charCodeAt()",
"codePointAt()",
"fromCharCode()",
"endsWith()",
"startsWith()",
"inclucdes()",
"localeCompare()",
"toLocaleLowerCase()",
"toLowerCase()",
"toLocaleUperCase()",
"toUpperCase()",
"trim()",
"trimStart()",
"trimEnd()"
];
export default _string;